### ISSUE TITLE
Minecraft executable does not close

### ISSUE THREAD

**Issue by quat1024** [ItsDizzy/DiscordRP#1]
Launching Minecraft 1.12.2 and Forge 2705 with MultiMC under Windows 7, loading DiscordRP 1.1 (according to Curse)

To reproduce:

1. Start Minecraft
2. Close Minecraft with the quit button on the main menu
3. Open Task Manager
4. Observe `javaw.exe` lingering around much, much longer than it normally does after closing the game

Normally it takes 3-5 seconds on my computer for javaw.exe to stop running after I close the game. However when I load DiscordRP, it seems to stick around indefinitely.

**Comment by paulhobbel** [comment]
Oh yes I see, thank you for reporting this issue, this is due to the DiscordRPCHandler thread not closing.

**Comment by paulhobbel** [comment]
This issue should be resolved in v1.2.0.13, curse is currently validating this version

**Comment by paulhobbel** [comment]
Could you try to confirm this is infact the case? If not I will do my best to fix it

**Comment by paulhobbel** [comment]
I guess the issue is resolved
